#!/usr/bin/env python3
"""Surface the ROUTES ALREADY TRIED for a lineage, at the top of every file in it.

⭐ OPERATOR'S POINT, 03 AUG 2026 (session #138): *"In the entry for a person you
should know what routes have already been tried -- or at least the routes checked
by others in the file."*

**Routes are REGIONAL, not personal**, which is why a per-person pointer does not
catch them. The failure that proved it: a session proposed "Antenati for Sondrio"
while working in one shard, and the measured answer -- *Antenati's holdings for
that comune BEGIN IN 1930, do not re-run* -- was sitting in a DIFFERENT PERSON'S
ENTRY in a SIBLING SHARD of the same lineage, recorded six weeks earlier. Two more
route re-proposals in the same sitting had the same shape.

`log_backlinks.py` fixes the PERSON axis (an entry points at its own prior
sessions). This fixes the ROUTE axis, and the scope is the LINEAGE -- a root file
plus its shards -- because that is the unit a route finding actually applies to.

⚠ **LINEAGE = A ROOT FILE PLUS EVERY FILE WHOSE NAME EXTENDS IT.** Derived from
the filenames themselves, not a hand-kept table: a file is a ROOT when no other
file's stem is a proper prefix of its stem. So a main lineage file and its
`_Collateral`, `_Deep`, `_Berkshire`, `_Clusters` shards are one lineage, which is
exactly the boundary the content-routing policy already splits on.

⚠ **THE BLOCK IS BLOCKQUOTED, AND THAT IS LOAD-BEARING.** A line beginning with a
bold span at line start IS the person-entry grammar (spec/entry-boundary). A
generated digest that quoted a bold name at line start would mint a phantom entry
and silently steal the following lines from a real one. Every emitted line is
prefixed with `> `.

⭐⭐ **THE REGISTER IS THE SOURCE, THE SCRAPE IS THE INTAKE (inverted 15 AUG 2026,
operator goals).** Originally this tool SCRAPED route statements out of entry prose
and quoted them into the digest — which duplicated text inside its own lineage
(5 of one file's 19 digest rows quoted that same file) and meant the knowledge's
only home was whichever person's entry it happened to be written in. Now:

  `Route_Register.md`   ONE curated file, a `## <lineage-root>` section per
                        lineage; rows are `- ⊘ <closed/bounded route>` and
                        `- ⏭ <open named route>`. THIS is where a route fact
                        lives (CLAUDE.method.md → "Knowledge routing").
  the digest blocks     rendered FROM the register by --apply — a view, no
                        longer a scrape.
  the scrape            demoted to intake: --candidates lists route-shaped
                        statements found in entry prose that are NOT yet in the
                        register (the burn-down worklist); --seed writes a first
                        register from them (one-time).

A vault with NO Route_Register.md keeps the legacy scrape-to-digest behavior, so
the tool stays upstream-safe and a fresh vault needs no config.

Usage:
    python3 scripts/route_digest.py                 # report (default)
    python3 scripts/route_digest.py --lineage Family_Tree_[REGION]
    python3 scripts/route_digest.py --apply         # write/refresh the blocks
    python3 scripts/route_digest.py --candidates    # prose statements not registered
    python3 scripts/route_digest.py --seed          # one-time: register from scrape
    python3 scripts/route_digest.py --heartbeat
"""
import argparse
import collections
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import vault_config  # noqa: E402

BEGIN = "<!-- ROUTE-DIGEST:BEGIN (generated by scripts/route_digest.py) -->"
END = "<!-- ROUTE-DIGEST:END -->"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)

BOLD_HEADER_RE = re.compile(r"^\*\*(.+?)\*\*")
META_ID_RE = re.compile(r"\bid:\s*(P-[0-9A-Za-z]+)")

# A CLOSURE is a statement that a route is spent. These are the dangerous ones to
# re-propose, so they sort first and are never truncated away before open routes.
CLOSURE_PAT = re.compile(
    r"⊘|do NOT re-run|do not re-run|not digit|un-digitiz|undigitiz|"
    r"exhausted|COVERAGE BOUNDARY|closed for the free layer|"
    r"structurally unsourceable|no onward route|route is closed|"
    r"NOT on Antenati|cannot be enumerated|index-only|INDEX-ONLY",
    re.I)
# An OPEN ROUTE is a named next action. Useful, but re-proposing one is harmless.
ROUTE_PAT = re.compile(r"⏭\s*\**\s*Routes?\b", re.I)

NOISE = re.compile(r"^\s*[-*]\s*$")


BASE_STEM = "Family_Tree"


def lineages(vault):
    """root stem -> [paths], derived from the filenames.

    ⚠ **THE BARE `Family_Tree` STEM IS EXCLUDED FROM ROOT CANDIDACY.** It is a
    prefix of every other shard name, so leaving it in collapses the whole vault
    into ONE lineage -- measured: 50 files, 184 statements, 1 group, which would
    have made the digest useless noise on every file. It keeps its own group."""
    paths = sorted(glob.glob(os.path.join(vault, "Family_Tree*.md")))
    stems = {os.path.basename(p)[: -len(".md")]: p for p in paths}
    roots = [s for s in stems
             if s != BASE_STEM
             and not any(o not in (s, BASE_STEM) and s.startswith(o + "_")
                         for o in stems)]
    out = collections.defaultdict(list)
    for stem, path in stems.items():
        owner = max((r for r in roots if stem == r or stem.startswith(r + "_")),
                    key=len, default=stem)
        out[owner].append(path)
    return {k: sorted(v) for k, v in out.items()}


def clause(line):
    """The finding, cleaned. Take the WHOLE bullet, not one sentence.

    ⚠ **A ONE-SENTENCE WINDOW LOSES THE FINDING, MEASURED.** The first version cut
    at the first full stop, so the vault's own worked example --
    *"NOT on Antenati, and that is a COVERAGE BOUNDARY, not a search failure.
    Antenati's holdings BEGIN IN 1930..."* -- was harvested with the boundary YEAR
    truncated away, i.e. the digest kept the alarm and dropped the fact. These
    bullets ARE the finding; keep them whole and cap on length instead."""
    t = line.strip()
    t = re.sub(r"^[-*]\s*", "", t)             # bullet marker
    t = re.sub(r"^\s*[-*]\s*", "", t)
    t = re.sub(r"\s+", " ", t)
    return t.strip(" -–—•")


def harvest(paths):
    """[(kind, text, person, file)] for one lineage."""
    found = []
    for path in paths:
        base = os.path.basename(path)[: -len(".md")]
        raw = open(path, encoding="utf-8").read()
        raw = BLOCK_RE.sub("", raw)          # never re-harvest our own output
        lines = raw.split("\n")
        starts = [i for i, l in enumerate(lines) if BOLD_HEADER_RE.match(l)]
        owner_at = {}
        for n, i in enumerate(starts):
            end = starts[n + 1] if n + 1 < len(starts) else len(lines)
            name = BOLD_HEADER_RE.match(lines[i]).group(1)
            name = re.sub(r"\s*\(.*$", "", name).strip()
            for k in range(i, end):
                owner_at[k] = name
        for k, line in enumerate(lines):
            if NOISE.match(line) or line.lstrip().startswith(">"):
                continue
            for kind, pat in (("closure", CLOSURE_PAT), ("route", ROUTE_PAT)):
                m = pat.search(line)
                if not m:
                    continue
                text = clause(line)
                if len(text) > 460:
                    text = text[:457].rsplit(" ", 1)[0] + "..."
                if 25 <= len(text):
                    found.append((kind, text, owner_at.get(k, ""), base))
                break
    return found


def dedupe(items):
    seen, out = set(), []
    for kind, text, person, base in items:
        key = _key(text)
        if key in seen:
            continue
        seen.add(key)
        out.append((kind, text, person, base))
    return out


def _key(text):
    return re.sub(r"[^a-z0-9]+", "", text.lower())[:90]


# a register row's trailing provenance (" — *person* `[file]`"), which is part of
# the curated TEXT but not of the finding — stripped before keying, or a short
# row would mismatch its own scraped source
_PROV_TAIL = re.compile(r"\s+—\s+\*[^*]+\*\s*(`\[[^\]]+\]`)?\s*$|\s+`\[[^\]]+\]`\s*$")


def _reg_key(text):
    return _key(_PROV_TAIL.sub("", text))


# --------------------------------------------------------------------------------------
# The register (the SOURCE since 15 AUG 2026; the scrape is intake)
# --------------------------------------------------------------------------------------
REGISTER = "Route_Register.md"
REG_ROW = re.compile(r"^-\s*(⊘|⏭)\s*(.+)$")

REGISTER_HEADER = """---
type: reference
tags: [genealogy, routes, register]
---

# Route Register — routes tried, bounded, and open, per lineage

**The curated home for ROUTE KNOWLEDGE** (CLAUDE.method.md → "Knowledge routing"):
facts about a SOURCE or REPOSITORY that hold whichever person you research —
coverage boundaries, spent searches, index-only collections, named next actions.
One `##` section per lineage root. Rows:

    - ⊘ <closed or bounded route — say the boundary FACT, not just the alarm>
    - ⏭ <open named route — the next action>

`scripts/route_digest.py --apply` renders each lineage's section into the
blockquoted digest at the head of its Family_Tree files; `--candidates` lists
route statements still sitting in entry prose that this register does not carry
(move them here as entries get touched). Keep rows ONE line each; put the
provenance (person, file or log) at the end after an em-dash.
"""


def load_register(vault):
    """{lineage-root: [(kind, text)]} from Route_Register.md; {} when absent."""
    path = os.path.join(vault, REGISTER)
    if not os.path.exists(path):
        return {}
    out, cur = {}, None
    for line in open(path, encoding="utf-8"):
        if line.startswith("## "):
            cur = line[3:].strip()
            out.setdefault(cur, [])
        elif cur is not None:
            m = REG_ROW.match(line.strip())
            if m:
                kind = "closure" if m.group(1) == "⊘" else "route"
                out[cur].append((kind, m.group(2).strip()))
    return out


def register_items(rows):
    """Register rows in the internal item shape (person/file provenance is part
    of the curated text, so those slots stay empty)."""
    return [(kind, text, "", "") for kind, text in rows]


def seed_register(vault, groups):
    """One-time: write Route_Register.md from the scrape. Refuses to overwrite."""
    path = os.path.join(vault, REGISTER)
    if os.path.exists(path):
        print(f"  {REGISTER} already exists — curate it; --seed never overwrites.")
        return 1
    out = [REGISTER_HEADER]
    n = 0
    for root, paths in sorted(groups.items()):
        items = dedupe(harvest(paths))
        if not items:
            continue
        out.append(f"\n## {root}\n")
        for kind, text, person, base in items:
            mark = "⊘" if kind == "closure" else "⏭"
            prov = f" — *{person}*" if person else ""
            out.append(f"- {mark} {text}{prov} `[{base}]`")
            n += 1
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"  seeded {REGISTER}: {n} row(s) across "
          f"{sum(1 for r in groups if dedupe(harvest(groups[r])))} lineage section(s).")
    print("  Rows are verbatim scrape output — curate on touch (boundary FACTS, one line).")
    return 0


def render(root, paths, items, cap):
    # ⚠ GROUP BY SHARD, PER KIND. Ordering by file position let the
    # alphabetically-first shard consume the whole cap, which is precisely how the
    # finding this tool exists for got truncated out of its own lineage's digest.
    def by_shard(kind, per):
        buckets = collections.OrderedDict()
        for it in items:
            if it[0] == kind:
                buckets.setdefault(it[3], []).append(it)
        return [i for b in buckets.values() for i in b[:per]]

    n_shards = max(1, len({i[3] for i in items}))
    per_shard = max(2, cap // n_shards + 1)
    closures = by_shard("closure", per_shard)
    routes = by_shard("route", per_shard)
    keep = closures + routes
    n_files = len(paths)
    out = [BEGIN,
           "> ### ⏮ ROUTES ALREADY TRIED IN THIS LINEAGE — read before proposing one",
           f"> *Generated by `scripts/route_digest.py` across all {n_files} file(s) of "
           f"`{root}`. **A route finding is REGIONAL**, so it may have been recorded on a "
           f"different person in a sibling shard — that is exactly the case this block exists "
           f"for. Regenerate with `--apply`; do not hand-edit.*",
           ">"]
    if closures:
        out.append("> **⊘ CLOSED / BOUNDED — do not re-run these:**")
        for _k, text, person, base in closures:
            who = f" — *{person}*" if person else ""
            src = f" `[{base}]`" if base else ""
            out.append(f"> - {text}{who}{src}")
        out.append(">")
    rest = [i for i in keep if i[0] == "route"]
    if rest:
        out.append("> **⏭ NAMED NEXT ROUTES (open):**")
        for _k, text, person, base in rest:
            who = f" — *{person}*" if person else ""
            src = f" `[{base}]`" if base else ""
            out.append(f"> - {text}{who}{src}")
    dropped = len(items) - len(keep)
    if dropped > 0:
        out.append(f">\n> *({dropped} further route statement(s) in this lineage not shown "
                   f"— raise `--cap` or grep the files.)*")
    out.append(END)
    return "\n".join(out) + "\n"


def insert(path, block):
    text = open(path, encoding="utf-8").read()
    text = BLOCK_RE.sub("", text)
    if text.startswith("---"):
        end = text.find("\n---", 3)
        cut = text.find("\n", end + 1) + 1 if end != -1 else 0
    else:
        cut = 0
    new = text[:cut] + ("\n" if cut and not text[cut:].startswith("\n") else "") + block + text[cut:]
    open(path, "w", encoding="utf-8").write(new)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--vault")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--lineage")
    ap.add_argument("--cap", type=int, default=18)
    ap.add_argument("--heartbeat", action="store_true")
    ap.add_argument("--candidates", action="store_true",
                    help="route-shaped statements in entry prose NOT in the register "
                         "(the burn-down worklist; requires Route_Register.md)")
    ap.add_argument("--seed", action="store_true",
                    help="one-time: write Route_Register.md from the scrape")
    args = ap.parse_args(argv)

    vault = vault_config.resolve_vault(args.vault)
    groups = lineages(vault)
    if args.lineage:
        groups = {k: v for k, v in groups.items() if k == args.lineage}

    if args.seed:
        return seed_register(vault, groups)

    register = load_register(vault)

    if args.candidates:
        if not register:
            print(f"  no {REGISTER} — run --seed first.")
            return 1
        total = 0
        for root, paths in sorted(groups.items()):
            reg_keys = {_reg_key(t) for _k, t in register.get(root, [])}
            fresh = [i for i in dedupe(harvest(paths)) if _key(i[1]) not in reg_keys]
            for kind, text, person, base in fresh:
                mark = "⊘" if kind == "closure" else "⏭"
                print(f"  {root}: - {mark} {text[:120]}"
                      + (f" — *{person}*" if person else "") + f" `[{base}]`")
            total += len(fresh)
        print(f"\n  ROUTE_CANDIDATES: {total} prose statement(s) not in {REGISTER} "
              f"(move each to the register when its entry is touched)")
        return 0

    total_items = total_lineages = 0
    for root, paths in sorted(groups.items()):
        # ⭐ the register section is the SOURCE when one exists; the scrape is the
        # legacy fallback so a register-less vault keeps working unchanged
        if root in register and register[root]:
            items = register_items(register[root])
            src = "register"
        else:
            items = dedupe(harvest(paths))
            src = "scrape"
        if not items:
            continue
        total_items += len(items)
        total_lineages += 1
        if args.heartbeat:
            continue
        if args.apply:
            block = render(root, paths, items, args.cap)
            for p in paths:
                insert(p, block)
        else:
            c = sum(1 for i in items if i[0] == "closure")
            print(f"  {root:52} {len(paths):2} file(s)  "
                  f"{c:3} closure  {len(items)-c:3} open route  [{src}]")

    if args.heartbeat:
        n_reg = sum(len(v) for v in register.values())
        print(f"ROUTE_DIGEST: {total_items} route statements across {total_lineages} "
              f"lineage(s); register rows {n_reg}"
              + ("" if register else f" (no {REGISTER}; scrape mode)")
              + "  [advisory; refresh with --apply]")
        return 0
    if args.apply:
        print(f"\n  APPLIED: route digest written into {total_lineages} lineage(s)"
              + (f" from {REGISTER}." if register else " from the scrape (no register)."))
    else:
        print(f"\n  {total_items} statements, {total_lineages} lineages. "
              f"(report only; --apply writes the blocks; --candidates for un-registered prose)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
