#!/usr/bin/env python3
"""Surface the ROUTES ALREADY TRIED for a lineage, at the top of every file in it.

⭐ OPERATOR'S POINT, 03 AUG 2026 (session #138): *"In the entry for a person you
should know what routes have already been tried -- or at least the routes checked
by others in the file."*

**Routes are REGIONAL, not personal**, which is why a per-person pointer does not
catch them. The failure that proved it: a session proposed "Antenati for Sondrio"
while working in one shard, and the measured answer -- *Antenati's holdings for
that comune BEGIN IN 1930, do not re-run* -- was sitting in a DIFFERENT PERSON'S
ENTRY in a SIBLING SHARD of the same lineage, recorded six weeks earlier. Two more
route re-proposals in the same sitting had the same shape.

`log_backlinks.py` fixes the PERSON axis (an entry points at its own prior
sessions). This fixes the ROUTE axis, and the scope is the LINEAGE -- a root file
plus its shards -- because that is the unit a route finding actually applies to.

⚠ **LINEAGE = A ROOT FILE PLUS EVERY FILE WHOSE NAME EXTENDS IT.** Derived from
the filenames themselves, not a hand-kept table: a file is a ROOT when no other
file's stem is a proper prefix of its stem. So a main lineage file and its
`_Collateral`, `_Deep`, `_Berkshire`, `_Clusters` shards are one lineage, which is
exactly the boundary the content-routing policy already splits on.

⚠ **THE BLOCK IS BLOCKQUOTED, AND THAT IS LOAD-BEARING.** A line beginning with a
bold span at line start IS the person-entry grammar (spec/entry-boundary). A
generated digest that quoted a bold name at line start would mint a phantom entry
and silently steal the following lines from a real one. Every emitted line is
prefixed with `> `.

Usage:
    python3 scripts/route_digest.py                 # report (default)
    python3 scripts/route_digest.py --lineage Family_Tree_[REGION]
    python3 scripts/route_digest.py --apply         # write/refresh the blocks
    python3 scripts/route_digest.py --heartbeat
"""
import argparse
import collections
import glob
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import vault_config  # noqa: E402

BEGIN = "<!-- ROUTE-DIGEST:BEGIN (generated by scripts/route_digest.py) -->"
END = "<!-- ROUTE-DIGEST:END -->"
BLOCK_RE = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?", re.S)

BOLD_HEADER_RE = re.compile(r"^\*\*(.+?)\*\*")
META_ID_RE = re.compile(r"\bid:\s*(P-[0-9A-Za-z]+)")

# A CLOSURE is a statement that a route is spent. These are the dangerous ones to
# re-propose, so they sort first and are never truncated away before open routes.
CLOSURE_PAT = re.compile(
    r"⊘|do NOT re-run|do not re-run|not digit|un-digitiz|undigitiz|"
    r"exhausted|COVERAGE BOUNDARY|closed for the free layer|"
    r"structurally unsourceable|no onward route|route is closed|"
    r"NOT on Antenati|cannot be enumerated|index-only|INDEX-ONLY",
    re.I)
# An OPEN ROUTE is a named next action. Useful, but re-proposing one is harmless.
ROUTE_PAT = re.compile(r"⏭\s*\**\s*Routes?\b", re.I)

NOISE = re.compile(r"^\s*[-*]\s*$")


BASE_STEM = "Family_Tree"


def lineages(vault):
    """root stem -> [paths], derived from the filenames.

    ⚠ **THE BARE `Family_Tree` STEM IS EXCLUDED FROM ROOT CANDIDACY.** It is a
    prefix of every other shard name, so leaving it in collapses the whole vault
    into ONE lineage -- measured: 50 files, 184 statements, 1 group, which would
    have made the digest useless noise on every file. It keeps its own group."""
    paths = sorted(glob.glob(os.path.join(vault, "Family_Tree*.md")))
    stems = {os.path.basename(p)[: -len(".md")]: p for p in paths}
    roots = [s for s in stems
             if s != BASE_STEM
             and not any(o not in (s, BASE_STEM) and s.startswith(o + "_")
                         for o in stems)]
    out = collections.defaultdict(list)
    for stem, path in stems.items():
        owner = max((r for r in roots if stem == r or stem.startswith(r + "_")),
                    key=len, default=stem)
        out[owner].append(path)
    return {k: sorted(v) for k, v in out.items()}


def clause(line):
    """The finding, cleaned. Take the WHOLE bullet, not one sentence.

    ⚠ **A ONE-SENTENCE WINDOW LOSES THE FINDING, MEASURED.** The first version cut
    at the first full stop, so the vault's own worked example --
    *"NOT on Antenati, and that is a COVERAGE BOUNDARY, not a search failure.
    Antenati's holdings BEGIN IN 1930..."* -- was harvested with the boundary YEAR
    truncated away, i.e. the digest kept the alarm and dropped the fact. These
    bullets ARE the finding; keep them whole and cap on length instead."""
    t = line.strip()
    t = re.sub(r"^[-*]\s*", "", t)             # bullet marker
    t = re.sub(r"^\s*[-*]\s*", "", t)
    t = re.sub(r"\s+", " ", t)
    return t.strip(" -–—•")


def harvest(paths):
    """[(kind, text, person, file)] for one lineage."""
    found = []
    for path in paths:
        base = os.path.basename(path)[: -len(".md")]
        raw = open(path, encoding="utf-8").read()
        raw = BLOCK_RE.sub("", raw)          # never re-harvest our own output
        lines = raw.split("\n")
        starts = [i for i, l in enumerate(lines) if BOLD_HEADER_RE.match(l)]
        owner_at = {}
        for n, i in enumerate(starts):
            end = starts[n + 1] if n + 1 < len(starts) else len(lines)
            name = BOLD_HEADER_RE.match(lines[i]).group(1)
            name = re.sub(r"\s*\(.*$", "", name).strip()
            for k in range(i, end):
                owner_at[k] = name
        for k, line in enumerate(lines):
            if NOISE.match(line) or line.lstrip().startswith(">"):
                continue
            for kind, pat in (("closure", CLOSURE_PAT), ("route", ROUTE_PAT)):
                m = pat.search(line)
                if not m:
                    continue
                text = clause(line)
                if len(text) > 460:
                    text = text[:457].rsplit(" ", 1)[0] + "..."
                if 25 <= len(text):
                    found.append((kind, text, owner_at.get(k, ""), base))
                break
    return found


def dedupe(items):
    seen, out = set(), []
    for kind, text, person, base in items:
        key = re.sub(r"[^a-z0-9]+", "", text.lower())[:90]
        if key in seen:
            continue
        seen.add(key)
        out.append((kind, text, person, base))
    return out


def render(root, paths, items, cap):
    # ⚠ GROUP BY SHARD, PER KIND. Ordering by file position let the
    # alphabetically-first shard consume the whole cap, which is precisely how the
    # finding this tool exists for got truncated out of its own lineage's digest.
    def by_shard(kind, per):
        buckets = collections.OrderedDict()
        for it in items:
            if it[0] == kind:
                buckets.setdefault(it[3], []).append(it)
        return [i for b in buckets.values() for i in b[:per]]

    n_shards = max(1, len({i[3] for i in items}))
    per_shard = max(2, cap // n_shards + 1)
    closures = by_shard("closure", per_shard)
    routes = by_shard("route", per_shard)
    keep = closures + routes
    n_files = len(paths)
    out = [BEGIN,
           "> ### ⏮ ROUTES ALREADY TRIED IN THIS LINEAGE — read before proposing one",
           f"> *Generated by `scripts/route_digest.py` across all {n_files} file(s) of "
           f"`{root}`. **A route finding is REGIONAL**, so it may have been recorded on a "
           f"different person in a sibling shard — that is exactly the case this block exists "
           f"for. Regenerate with `--apply`; do not hand-edit.*",
           ">"]
    if closures:
        out.append("> **⊘ CLOSED / BOUNDED — do not re-run these:**")
        for _k, text, person, base in closures:
            who = f" — *{person}*" if person else ""
            out.append(f"> - {text}{who} `[{base}]`")
        out.append(">")
    rest = [i for i in keep if i[0] == "route"]
    if rest:
        out.append("> **⏭ NAMED NEXT ROUTES (open):**")
        for _k, text, person, base in rest:
            who = f" — *{person}*" if person else ""
            out.append(f"> - {text}{who} `[{base}]`")
    dropped = len(items) - len(keep)
    if dropped > 0:
        out.append(f">\n> *({dropped} further route statement(s) in this lineage not shown "
                   f"— raise `--cap` or grep the files.)*")
    out.append(END)
    return "\n".join(out) + "\n"


def insert(path, block):
    text = open(path, encoding="utf-8").read()
    text = BLOCK_RE.sub("", text)
    if text.startswith("---"):
        end = text.find("\n---", 3)
        cut = text.find("\n", end + 1) + 1 if end != -1 else 0
    else:
        cut = 0
    new = text[:cut] + ("\n" if cut and not text[cut:].startswith("\n") else "") + block + text[cut:]
    open(path, "w", encoding="utf-8").write(new)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--vault")
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("--lineage")
    ap.add_argument("--cap", type=int, default=18)
    ap.add_argument("--heartbeat", action="store_true")
    args = ap.parse_args(argv)

    vault = vault_config.resolve_vault(args.vault)
    groups = lineages(vault)
    if args.lineage:
        groups = {k: v for k, v in groups.items() if k == args.lineage}

    total_items = total_lineages = 0
    for root, paths in sorted(groups.items()):
        items = dedupe(harvest(paths))
        if not items:
            continue
        total_items += len(items)
        total_lineages += 1
        if args.heartbeat:
            continue
        if args.apply:
            block = render(root, paths, items, args.cap)
            for p in paths:
                insert(p, block)
        else:
            c = sum(1 for i in items if i[0] == "closure")
            print(f"  {root:52} {len(paths):2} file(s)  "
                  f"{c:3} closure  {len(items)-c:3} open route")

    if args.heartbeat:
        print(f"ROUTE_DIGEST: {total_items} route statements across {total_lineages} "
              f"lineage(s)  [advisory; refresh with --apply]")
        return 0
    if args.apply:
        print(f"\n  APPLIED: route digest written into {total_lineages} lineage(s).")
    else:
        print(f"\n  {total_items} statements, {total_lineages} lineages. "
              f"(report only; --apply writes the blocks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
